name: Update Current Branch

on:
  push:
    branches:
      - '*'

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current branch name
      id: get_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Switch to updated branch
      run: git checkout ${{ steps.get_branch.outputs.branch }}

    - name: Pull latest changes
      run: git pull origin ${{ steps.get_branch.outputs.branch }}

    - name: Push changes to updated branch
      run: git push origin ${{ steps.get_branch.outputs.branch }}
